name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Test 2
      id: test-2
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 2
        setup-command: javac Perulangan.java
        command: java Perulangan
        input: '1'
        expected-output: '2'
        comparison-method: exact
        timeout: 10
        max-score: 50
    - name: Test 4
      id: test-4
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Test 4
        setup-command: javac Perulangan.java
        command: java Perulangan
        input: '4'
        expected-output: '8'
        comparison-method: exact
        timeout: 10
        max-score: 50
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        TEST-2_RESULTS: "${{steps.test-2.outputs.result}}"
        TEST-4_RESULTS: "${{steps.test-4.outputs.result}}"
      with:
        runners: test-2,test-4
